### ISSUE TITLE
[Question] An error with the same repo guideline

### ISSUE THREAD

**Issue by ghost** [google-research/deduplicate-text-datasets#36]
Hi 
I'm following the same guideline to do data deduplication for the wiki40 dataset, 
in this step of building the suffix array, with this command `python3 scripts/make_suffix_array.py data/wiki40b.test`
In the data folder I have the .size and .test files
and the command generate 8 bin files then it throws that error.
`./target/debug/dedup_dataset make-part --data-file data/wiki40b.test --start-byte 0 --end-byte 129292893
./target/debug/dedup_dataset make-part --data-file data/wiki40b.test --start-byte 129192893 --end-byte 258485786
./target/debug/dedup_dataset make-part --data-file data/wiki40b.test --start-byte 258385786 --end-byte 387678679
./target/debug/dedup_dataset make-part --data-file data/wiki40b.test --start-byte 387578679 --end-byte 516771573
Waiting for jobs to finish
Checking all wrote correctly
FACT 4.0 517171572.0 517171572
FACT 4.0 517171572.0 517171572
FACT 4.0 517171572.0 517171572
FACT 4.0 516771576.0 516771576
Rerunning 0 jobs because they failed.
Merging suffix trees
rm: cannot remove 'tmp/out.table.bin.*': No such file or directory
./target/debug/dedup_dataset merge --output-file tmp/out.table.bin --suffix-path data/wiki40b.test.part.0-129292893 --suffix-path data/wiki40b.test.part.129192893-258485786 --suffix-path data/wiki40b.test.part.258385786-387678679 --suffix-path data/wiki40b.test.part.387578679-516771573 --num-threads 16
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread '<unnamed>' panicked at src/main.rs:1252:125:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
thread 'main' panicked at /home/ubuntu/.cargo/registry/src/index.crates.io-6f17d22bba15001f/crossbeam-0.3.2/src/scoped.rs:34:43:
called `Result::unwrap()` on an `Err` value: Any { .. }
Something went wrong with merging.
Please check that you ran with ulimit -Sn 100000`
I tried with this param  `ulimit -Sn 100000`
and I had the same error,  
Can you help me to figure it out
Thanks

**Comment by tanfoster92** [comment]
I also get this.

I am running on Ubuntu running in wsl. I will try and get more information.

**Comment by tanfoster92** [comment]
So I have the solution, in src/main.rs:1252, it tries to create a file at {path}/{File}.table.bin.out.{index}. If {path} does not exist it cannot create that path. I solved this by running `mkdir tmp` in the directory I was running that step from and the process completed completely. I am not sure if this is an issue with my OS since I am running wsl or if I needed to run these commands as a super user. A simple fix for this could be to ensure the folder exists in code and create it if not. Otherwise my process will work.

**Comment by thak123** [comment]
> So I have the solution, in src/main.rs:1252, it tries to create a file at {path}/{File}.table.bin.out.{index}. If {path} does not exist it cannot create that path. I solved this by running `mkdir tmp` in the directory I was running that step from and the process completed completely. I am not sure if this is an issue with my OS since I am running wsl or if I needed to run these commands as a super user. A simple fix for this could be to ensure the folder exists in code and create it if not. Otherwise my process will work.

Yes worked for me. Thanks

**Comment by EdwinRou** [comment]
> So I have the solution, in src/main.rs:1252, it tries to create a file at {path}/{File}.table.bin.out.{index}. If {path} does not exist it cannot create that path. I solved this by running `mkdir tmp` in the directory I was running that step from and the process completed completely. I am not sure if this is an issue with my OS since I am running wsl or if I needed to run these commands as a super user. A simple fix for this could be to ensure the folder exists in code and create it if not. Otherwise my process will work.

you saved my life thx

**Comment by ftgreat** [comment]
you saved my life thx
